/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.example.daggernameconfict

import javax.inject.Inject

class App {

    @Inject
    lateinit var create: Create

    init {

        DaggerExampleComponent.create().inject(this)
    }

    val greeting: String
        get() {
            return "Hello ${create.greet()}"
        }
}

fun main() {
    println(App().greeting)
}
